# This is a basic workflow to help you get started with Actions

name: AKS Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker build
      run: docker build -t selise-assessment:'${{github.sha}}' .
    
    - name: docker login
      run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'
      
    - name: tag docker image
      run: docker tag selise-assessment:'${{github.sha}}' '${{secrets.DOCKER_LOGIN}}'/selise-assessment:'${{github.sha}}'
    
    - name: push docker image
      run: docker push '${{secrets.DOCKER_LOGIN}}'/selise-assessment:'${{github.sha}}'
      
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
        creds: '${{secrets.AZURE_CREDENTIALS}}'
        resource-group: selise-assessment
        cluster-name: selise-assessment

  # Create K8s secrets to pull images
    - name: Create secret in Kubernetes cluster
      uses: Azure/k8s-create-secret@v1.1
      with:
        container-registry-url: https://index.docker.io/v1/
        container-registry-username: '${{secrets.DOCKER_LOGIN}}'
        container-registry-password:  '${{secrets.DOCKER_PASSWORD}}'
        secret-type: docker-registry
        secret-name: docker-image-pull-secret
        
      # Deploy to k8s cluster
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:        
        manifests: |
          k8s/deployment.yml
          k8s/service.yml
          k8s/hpa.yml
          k8s/ingress.yaml
        images: '${{secrets.DOCKER_LOGIN}}/selise-assessment:${{github.sha}}'
        imagepullsecrets: docker-image-pull-secret
        action: deploy
        
    
        
    
